"""Export the original prompt recordings of a monitor case set from Hugging Face Parquet shards.

The latent cache stores no waveforms, and `monitor.py` scores speaker similarity against codec-decoded
prompts (SIM-r). Published zero-shot TTS numbers use the original prompt audio (SIM-o), so this writes
each case's prompt as a WAV with the training-time loudness normalization applied.

  HF_TOKEN=... python scripts/export_case_audio.py --repo ORG/DATASET --cases runs/nano/monitor/cases.json \
      --cache data/corpus/merged --output data/corpus/eval-audio
"""

import argparse
import io
import json
import os
import shutil
from pathlib import Path

import pyarrow.parquet as pq
import soundfile as sf
from huggingface_hub import hf_hub_download

from dacvae_tts.codec import read_audio


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--repo", required=True)
    parser.add_argument("--cases", required=True)
    parser.add_argument("--cache", required=True, help="Merged cache; supplies the loudness setting")
    parser.add_argument("--output", required=True)
    parser.add_argument("--audio-column", default="audio")
    parser.add_argument("--sample-rate", type=int, default=48000)
    args = parser.parse_args()

    meta = json.loads((Path(args.cache) / "metadata.json").read_text())
    loudness = meta.get("loudness_lufs")
    cases = json.loads(Path(args.cases).read_text())
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    wanted = {}
    for case in cases:
        # Row ids were generated by `prepare` as "<file relative to the dataset dir>:<row index>".
        for key in ("prompt_uid", "uid"):
            file, row = case[key].rsplit(":", 1)
            wanted.setdefault(file, set()).add(int(row))
    token = os.environ.get("HF_TOKEN")
    scratch = output / "_download"
    for file, rows in sorted(wanted.items()):
        path = hf_hub_download(args.repo, file, repo_type="dataset", token=token, local_dir=scratch)
        table = pq.ParquetFile(path)
        index = 0
        for batch in table.iter_batches(batch_size=256, columns=[args.audio_column]):
            for row in batch.to_pylist():
                if index in rows:
                    audio = read_audio(
                        io.BytesIO(row[args.audio_column]["bytes"]), args.sample_rate, loudness
                    )
                    name = f"{file}:{index}".replace("/", "_").replace(":", "_")
                    sf.write(output / f"{name}.wav", audio.numpy(), args.sample_rate)
                index += 1
        Path(path).unlink()
    shutil.rmtree(scratch, ignore_errors=True)
    print(f"wrote {len(list(output.glob('*.wav')))} recordings to {output}")


if __name__ == "__main__":
    main()
